language: objective-c
osx_image: xcode7.1
before_install:
  - gem install xcpretty
before_script:
  - set -o pipefail
script:
  - xcodebuild -project SingletonDemo/SingletonDemo.xcodeproj -scheme SingletonDemo -destination 'platform=iOS Simulator,name=iPhone 6s' -sdk iphonesimulator test | xcpretty -c
